import type { Locale } from '../../i18n.ts'

export type ConvolutionLessonId = 'discrete' | 'probability' | 'signal' | 'image-kernel' | 'polynomial' | 'continuous'

export type ConvolutionLessonCopy = {
  title: string
  what: string
  why: string
  formula: string
  formulaTex: string
  watch: string
}

type LabelMap = Record<string, string>

export type ConvolutionUiCopy = {
  moduleEyebrow: string
  homeSummary: string
  relatedModulesAria: string
  relatedPrefix: string
  controls: string
  seeing: string
  why: string
  formula: string
  values: string
  watch: string
  preset: string
  play: string
  pause: string
  reset: string
  playbackProgress: string
  exportPng: string
  speed: string
  add: string
  yes: string
  no: string
  undefinedValue: string
  noOverlap: string
  operationNote: string
  uploadLocalImage: string
  exportOutputImage: string
  imageProcessingHelp: string
  selectedFunctions: string
  uploadFailed: string
  couldNotReadImage: string
  labels: LabelMap
  canvas: LabelMap
  options: LabelMap
}

export const convolutionLessonCopy: Record<Locale, Record<ConvolutionLessonId, ConvolutionLessonCopy>> = {
  en: {
    discrete: {
      title: 'Discrete Convolution',
      what: 'b is flipped, shifted across a, overlapping values are multiplied, and those products are summed.',
      why: 'This same operation appears in probability, signal filtering, image processing, polynomial multiplication, and Fourier analysis.',
      formula: 'y[k] = sum_i a[i] b[k - i]',
      formulaTex: 'y[k]=\\sum_i a[i]b[k-i]',
      watch: 'If the kernel is symmetric, flipping it does not change it. If it is asymmetric, convolution and correlation differ.',
    },
    probability: {
      title: 'Probability Sum',
      what: 'Each output probability collects all pairs of outcomes that add to the same sum.',
      why: 'Adding independent random variables combines their distributions by convolution.',
      formula: 'P(S = s) = sum_x P_X(x) P_Y(s - x)',
      formulaTex: 'P(S=s)=\\sum_x P_X(x)P_Y(s-x)',
      watch: 'The middle sums often have more combinations, which is why two dice are more likely to sum to 7 than to 2 or 12.',
    },
    signal: {
      title: 'Signal Filtering',
      what: 'The kernel slides over the signal. At each position, the output is a weighted sum of nearby input values.',
      why: 'Changing the kernel changes the filter: averaging smooths, differences highlight changes, and other kernels can sharpen or detect edges.',
      formula: 'y[k] = sum_i signal[i] kernel[k - i]',
      formulaTex: 'y[k]=\\sum_i x[i]h[k-i]',
      watch: 'Larger smoothing kernels reduce noise but can blur sharp features. Convolution flips the kernel; correlation does not.',
    },
    'image-kernel': {
      title: 'Image Kernel',
      what: 'A small kernel looks at a pixel’s neighborhood. The output pixel is a weighted sum of nearby pixels.',
      why: 'Blur, sharpen, emboss, and edge detection can all be expressed as small convolution kernels.',
      formula: 'out[x,y] = sum_u sum_v image[x-u,y-v] kernel[u,v]',
      formulaTex: '\\text{out}[x,y]=\\sum_u\\sum_v I[x-u,y-v]K[u,v]',
      watch: 'Many image-processing kernels are symmetric, but asymmetric kernels reveal the difference between convolution and correlation.',
    },
    polynomial: {
      title: 'Polynomial Multiplication',
      what: 'Each product term contributes to a coefficient whose power is the sum of the two original powers.',
      why: 'Collecting equal powers is the same sum pattern as discrete convolution.',
      formula: 'c[k] = sum_i a[i] b[k - i]',
      formulaTex: 'c[k]=\\sum_i a_i b_{k-i}',
      watch: 'The coefficient of x^k collects all pairs i + j = k. Coefficients use ascending powers.',
    },
    continuous: {
      title: 'Continuous Convolution',
      what: 'One function is flipped and shifted. At each shift, the overlap product is integrated.',
      why: 'Continuous convolution is the smooth analogue of discrete convolution. It appears in probability, signal processing, differential equations, and Fourier analysis.',
      formula: '(f * g)(t) = integral f(tau) g(t - tau) d tau',
      formulaTex: '(f*g)(t)=\\int f(\\tau)g(t-\\tau)\\,d\\tau',
      watch: 'The output is large where the flipped-and-shifted function overlaps strongly with the other function.',
    },
  },
  zh: {
    discrete: {
      title: '离散卷积',
      what: 'b 先翻转，再沿着 a 平移；重叠的值逐项相乘，最后把乘积相加。',
      why: '同一个操作会出现在概率、信号滤波、图像处理、多项式乘法和傅里叶分析里。',
      formula: 'y[k] = sum_i a[i] b[k - i]',
      formulaTex: 'y[k]=\\sum_i a[i]b[k-i]',
      watch: '如果 kernel 对称，翻转前后没有区别；如果不对称，卷积和相关会得到不同结果。',
    },
    probability: {
      title: '概率和',
      what: '每个输出概率都会收集所有加起来等于同一个和的结果对。',
      why: '独立随机变量相加时，它们的分布会通过卷积组合。',
      formula: 'P(S = s) = sum_x P_X(x) P_Y(s - x)',
      formulaTex: 'P(S=s)=\\sum_x P_X(x)P_Y(s-x)',
      watch: '中间的和通常有更多组合，所以两个骰子更容易掷出 7，而不是 2 或 12。',
    },
    signal: {
      title: '信号滤波',
      what: 'kernel 沿着信号滑动；每个位置的输出都是邻近输入值的加权和。',
      why: '改变 kernel 就是在改变滤波器：平均会平滑，差分会突出变化，其它 kernel 可以锐化或检测边缘。',
      formula: 'y[k] = sum_i signal[i] kernel[k - i]',
      formulaTex: 'y[k]=\\sum_i x[i]h[k-i]',
      watch: '更大的平滑 kernel 会减少噪声，但也可能模糊尖锐特征。卷积会翻转 kernel，相关不会。',
    },
    'image-kernel': {
      title: '图像卷积核',
      what: '小 kernel 查看某个像素周围的邻域；输出像素是邻近像素的加权和。',
      why: '模糊、锐化、浮雕和边缘检测都可以用小卷积核表达。',
      formula: 'out[x,y] = sum_u sum_v image[x-u,y-v] kernel[u,v]',
      formulaTex: '\\text{out}[x,y]=\\sum_u\\sum_v I[x-u,y-v]K[u,v]',
      watch: '许多图像处理 kernel 是对称的，但不对称 kernel 能显示卷积和相关的区别。',
    },
    polynomial: {
      title: '多项式乘法',
      what: '每个乘积项都会贡献到一个系数中；这个系数的次数等于两个原次数之和。',
      why: '合并同次幂项，就是和离散卷积相同的求和模式。',
      formula: 'c[k] = sum_i a[i] b[k - i]',
      formulaTex: 'c[k]=\\sum_i a_i b_{k-i}',
      watch: 'x^k 的系数会收集所有 i + j = k 的项。这里的系数按升幂排列。',
    },
    continuous: {
      title: '连续卷积',
      what: '一个函数先翻转再平移；每个平移位置都对重叠乘积做积分。',
      why: '连续卷积是离散卷积的平滑版本，出现在概率、信号处理、微分方程和傅里叶分析里。',
      formula: '(f * g)(t) = integral f(tau) g(t - tau) d tau',
      formulaTex: '(f*g)(t)=\\int f(\\tau)g(t-\\tau)\\,d\\tau',
      watch: '当翻转并平移后的函数和另一个函数强烈重叠时，输出会变大。',
    },
  },
}

export const convolutionUiCopy: Record<Locale, ConvolutionUiCopy> = {
  en: {
    moduleEyebrow: 'Convolution',
    homeSummary: 'Convolution combines two objects by sliding one across the other, multiplying overlapping parts, and summing the result.',
    relatedModulesAria: 'Related modules',
    relatedPrefix: 'Related',
    controls: 'Controls',
    seeing: 'What you are seeing',
    why: 'Why it matters',
    formula: 'Current formula',
    values: 'Current values',
    watch: 'Watch for',
    preset: 'Preset',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset animation',
    playbackProgress: 'Playback progress',
    exportPng: 'Export PNG',
    speed: 'speed',
    add: 'add',
    yes: 'yes',
    no: 'no',
    undefinedValue: 'undefined',
    noOverlap: 'no overlap',
    operationNote: 'Convolution flips the kernel before sliding. Correlation slides the kernel without flipping. For symmetric kernels, both give the same result.',
    uploadLocalImage: 'upload local image',
    exportOutputImage: 'Export output image',
    imageProcessingHelp: 'Click either image to inspect a pixel neighborhood. Image processing stays local in the browser.',
    selectedFunctions: 'selected functions',
    uploadFailed: 'Image upload failed.',
    couldNotReadImage: 'Could not read uploaded image.',
    labels: {
      sequenceA: 'sequence a',
      kernelB: 'kernel b',
      mode: 'mode',
      operation: 'operation',
      shiftOutputIndex: 'shift / output index',
      currentK: 'current k',
      yk: 'y[k]',
      overlapCount: 'overlap count',
      kernelSymmetric: 'kernel symmetric',
      terms: 'terms',
      sumS: 'sum s',
      selectedSum: 'selected sum',
      probabilityAtSum: 'P(X + Y = s)',
      ex: 'E[X]',
      ey: 'E[Y]',
      exPlusY: 'E[X + Y]',
      varXPlusY: 'Var(X + Y)',
      signal: 'signal',
      kernel: 'kernel',
      boundaryMode: 'boundary mode',
      length: 'length',
      gaussianSigma: 'gaussian sigma',
      noiseAmplitude: 'noise amplitude',
      seed: 'seed',
      kernelPosition: 'kernel position',
      currentIndex: 'current index',
      kernelSize: 'kernel size',
      outputValue: 'output value',
      sampleImage: 'sample image',
      uploadImage: 'uploaded image',
      kernelPreset: 'kernel preset',
      gridSize: 'kernel size',
      normalizeKernel: 'normalize kernel',
      preserveAlpha: 'preserve alpha',
      grayscaleBeforeApply: 'grayscale before apply',
      selectedPixel: 'selected pixel',
      kernelSum: 'kernel sum',
      outputRgb: 'output RGB',
      inputImage: 'input image',
      outputImage: 'output image',
      aCoefficients: 'A coefficients',
      bCoefficients: 'B coefficients',
      coefficientK: 'coefficient k',
      degreeOfResult: 'degree of result',
      ascendingPowersHelp: 'Ascending powers: [1, 2, 3] means 1 + 2x + 3x^2.',
      functionF: 'function f',
      functionG: 'function g',
      shiftT: 'shift t',
      integrationSamples: 'integration samples',
      currentT: 'current t',
      convolutionValue: '(f * g)(t)',
      sampleCount: 'sample count',
      fPreset: 'f preset',
      gPreset: 'g preset',
    },
    canvas: {
      discreteAria: 'Discrete convolution scene showing flip, shift, overlap, multiply, sum, and output bars.',
      probabilityAria: 'Probability sum explorer showing source distributions, pair heatmap, and output distribution.',
      signalAria: 'Signal filtering scene showing original signal, kernel window, products, and filtered output.',
      polynomialAria: 'Polynomial multiplication grid and coefficient convolution output.',
      continuousAria: 'Continuous convolution scene showing f, flipped and shifted g, product area, and output curve.',
      aWithFlippedB: 'a (teal) with flipped b (purple)',
      aWithDirectB: 'a (teal) with b sliding directly (purple)',
      overlapProducts: 'overlap products for full index',
      outputY: 'output y',
      pairsForSum: 'pairs that add to selected sum',
      inputSignal: 'input signal',
      kernelFlipped: 'kernel (flipped for convolution)',
      kernelCorrelation: 'kernel (correlation order)',
      filteredOutput: 'filtered output',
      polynomialGrid: 'multiplication grid: row power + column power = output power',
      productCoefficients: 'product coefficients c',
    },
    options: {
      convolution: 'convolution',
      correlation: 'correlation',
      full: 'full',
      same: 'same',
      valid: 'valid',
      zero: 'zero',
      clamp: 'clamp',
      wrap: 'wrap',
      impulse: 'impulse',
      'impulse identity': 'impulse identity',
      'box blur': 'box blur',
      'edge detector': 'edge detector',
      'small custom': 'small custom',
      'asymmetric kernel': 'asymmetric kernel',
      'symmetric kernel': 'symmetric kernel',
      'fair d6 + fair d6': 'fair d6 + fair d6',
      'biased coin + biased coin': 'biased coin + biased coin',
      'd4 + d8': 'd4 + d8',
      'custom small distribution': 'custom small distribution',
      'repeated dice sum': 'repeated dice sum',
      'binomial-like coin flips': 'binomial-like coin flips',
      'The middle sums have the most pairs.': 'The middle sums have the most pairs.',
      'Each sum collects the matching coin outcomes.': 'Each sum collects the matching coin outcomes.',
      'Different supports produce a trapezoid-like sum distribution.': 'Different supports produce a trapezoid-like sum distribution.',
      'Repeated values act like larger probability mass.': 'Repeated values act like larger probability mass.',
      'Repeated convolution builds a bell-shaped dice total.': 'Repeated convolution builds a bell-shaped dice total.',
      'Many independent binary choices concentrate near the center.': 'Many independent binary choices concentrate near the center.',
      step: 'step',
      sine: 'sine',
      'mixed sine': 'mixed sine',
      'noisy sine': 'noisy sine',
      'random spikes': 'random spikes',
      identity: 'identity',
      'moving average 3': 'moving average 3',
      'moving average 5': 'moving average 5',
      gaussian: 'gaussian',
      difference: 'difference',
      'edge detect': 'edge detect',
      'sharpen-like 1D': 'sharpen-like 1D',
      gradient: 'gradient',
      checkerboard: 'checkerboard',
      'simple face-like pattern': 'simple face-like pattern',
      noise: 'noise',
      'edge shapes': 'edge shapes',
      'uploaded image': 'uploaded image',
      'gaussian blur': 'gaussian blur',
      sharpen: 'sharpen',
      emboss: 'emboss',
      'sobel x': 'sobel x',
      'sobel y': 'sobel y',
      '(1 + x)(1 + x)': '(1 + x)(1 + x)',
      '(1 + x)^2': '(1 + x)^2',
      '(1 + x)^3 step': '(1 + x)^3 step',
      'asymmetric polynomials': 'asymmetric polynomials',
      'negative coefficients': 'negative coefficients',
      'zero coefficients': 'zero coefficients',
      rectangle: 'rectangle',
      triangle: 'triangle',
      'exponential decay': 'exponential decay',
      'two bumps': 'two bumps',
    },
  },
  zh: {
    moduleEyebrow: '卷积',
    homeSummary: '卷积把两个对象通过滑动、重叠相乘、再求和组合起来。',
    relatedModulesAria: '相关模块',
    relatedPrefix: '相关',
    controls: '控制',
    seeing: '你正在看到什么',
    why: '为什么重要',
    formula: '当前公式',
    values: '当前数值',
    watch: '注意观察',
    preset: '预设',
    play: '播放',
    pause: '暂停',
    reset: '重置动画',
    playbackProgress: '播放进度',
    exportPng: '导出 PNG',
    speed: '速度',
    add: '添加',
    yes: '是',
    no: '否',
    undefinedValue: '未定义',
    noOverlap: '没有重叠',
    operationNote: '卷积会先翻转 kernel 再滑动；相关不会翻转，直接滑动。对称 kernel 下，两者结果相同。',
    uploadLocalImage: '上传本地图片',
    exportOutputImage: '导出输出图像',
    imageProcessingHelp: '点击任一图像可检查像素邻域。图像处理全部在浏览器本地完成。',
    selectedFunctions: '选中的函数',
    uploadFailed: '图片上传失败。',
    couldNotReadImage: '无法读取上传的图片。',
    labels: {
      sequenceA: '序列 a',
      kernelB: 'kernel b',
      mode: '模式',
      operation: '操作',
      shiftOutputIndex: '平移 / 输出索引',
      currentK: '当前 k',
      yk: 'y[k]',
      overlapCount: '重叠项数',
      kernelSymmetric: 'kernel 是否对称',
      terms: '展开项',
      sumS: '和 s',
      selectedSum: '选中的和',
      probabilityAtSum: 'P(X + Y = s)',
      ex: 'E[X]',
      ey: 'E[Y]',
      exPlusY: 'E[X + Y]',
      varXPlusY: 'Var(X + Y)',
      signal: '信号',
      kernel: 'kernel',
      boundaryMode: '边界模式',
      length: '长度',
      gaussianSigma: '高斯 sigma',
      noiseAmplitude: '噪声幅度',
      seed: '随机种子',
      kernelPosition: 'kernel 位置',
      currentIndex: '当前索引',
      kernelSize: 'kernel 大小',
      outputValue: '输出值',
      sampleImage: '示例图像',
      uploadImage: '已上传图像',
      kernelPreset: 'kernel 预设',
      gridSize: 'kernel 大小',
      normalizeKernel: '归一化 kernel',
      preserveAlpha: '保留 alpha',
      grayscaleBeforeApply: '先转灰度',
      selectedPixel: '选中像素',
      kernelSum: 'kernel 总和',
      outputRgb: '输出 RGB',
      inputImage: '输入图像',
      outputImage: '输出图像',
      aCoefficients: 'A 系数',
      bCoefficients: 'B 系数',
      coefficientK: '系数 k',
      degreeOfResult: '结果次数',
      ascendingPowersHelp: '升幂排列：[1, 2, 3] 表示 1 + 2x + 3x^2。',
      functionF: '函数 f',
      functionG: '函数 g',
      shiftT: '平移 t',
      integrationSamples: '积分采样数',
      currentT: '当前 t',
      convolutionValue: '(f * g)(t)',
      sampleCount: '采样数',
      fPreset: 'f 预设',
      gPreset: 'g 预设',
    },
    canvas: {
      discreteAria: '离散卷积场景，显示翻转、平移、重叠、相乘、求和以及输出柱。',
      probabilityAria: '概率和场景，显示源分布、组合热力图和输出分布。',
      signalAria: '信号滤波场景，显示原始信号、kernel 窗口、乘积和滤波输出。',
      polynomialAria: '多项式乘法网格和系数卷积输出。',
      continuousAria: '连续卷积场景，显示 f、翻转并平移的 g、乘积面积和输出曲线。',
      aWithFlippedB: 'a（青色）与翻转后的 b（紫色）',
      aWithDirectB: 'a（青色）与直接滑动的 b（紫色）',
      overlapProducts: '完整索引的重叠乘积',
      outputY: '输出 y',
      pairsForSum: '加起来等于选中和的组合',
      inputSignal: '输入信号',
      kernelFlipped: 'kernel（卷积时翻转）',
      kernelCorrelation: 'kernel（相关顺序）',
      filteredOutput: '滤波输出',
      polynomialGrid: '乘法网格：行次数 + 列次数 = 输出次数',
      productCoefficients: '乘积系数 c',
    },
    options: {
      convolution: '卷积',
      correlation: '相关',
      full: 'full',
      same: 'same',
      valid: 'valid',
      zero: '补零',
      clamp: '钳制',
      wrap: '环绕',
      impulse: '冲激',
      'impulse identity': '冲激恒等',
      'box blur': '盒式平滑',
      'edge detector': '边缘检测',
      'small custom': '小型自定义',
      'asymmetric kernel': '非对称 kernel',
      'symmetric kernel': '对称 kernel',
      'fair d6 + fair d6': '公平 d6 + 公平 d6',
      'biased coin + biased coin': '偏置硬币 + 偏置硬币',
      'd4 + d8': 'd4 + d8',
      'custom small distribution': '小型自定义分布',
      'repeated dice sum': '重复骰子求和',
      'binomial-like coin flips': '类似二项分布的硬币',
      'The middle sums have the most pairs.': '中间的和有最多组合。',
      'Each sum collects the matching coin outcomes.': '每个和都会收集匹配的硬币结果。',
      'Different supports produce a trapezoid-like sum distribution.': '不同支撑会产生近似梯形的和分布。',
      'Repeated values act like larger probability mass.': '重复值相当于更大的概率质量。',
      'Repeated convolution builds a bell-shaped dice total.': '重复卷积会形成钟形的骰子总和分布。',
      'Many independent binary choices concentrate near the center.': '许多独立二元选择会集中在中间。',
      step: '阶跃',
      sine: '正弦',
      'mixed sine': '混合正弦',
      'noisy sine': '含噪正弦',
      'random spikes': '随机尖峰',
      identity: '恒等',
      'moving average 3': '移动平均 3',
      'moving average 5': '移动平均 5',
      gaussian: '高斯',
      difference: '差分',
      'edge detect': '边缘检测',
      'sharpen-like 1D': '一维锐化',
      gradient: '渐变',
      checkerboard: '棋盘格',
      'simple face-like pattern': '简易人脸图案',
      noise: '噪声',
      'edge shapes': '边缘形状',
      'uploaded image': '已上传图像',
      'gaussian blur': '高斯模糊',
      sharpen: '锐化',
      emboss: '浮雕',
      'sobel x': 'Sobel X',
      'sobel y': 'Sobel Y',
      '(1 + x)(1 + x)': '(1 + x)(1 + x)',
      '(1 + x)^2': '(1 + x)^2',
      '(1 + x)^3 step': '(1 + x)^3 分步',
      'asymmetric polynomials': '非对称多项式',
      'negative coefficients': '负系数',
      'zero coefficients': '含零系数',
      rectangle: '矩形',
      triangle: '三角形',
      'exponential decay': '指数衰减',
      'two bumps': '两个凸起',
    },
  },
}
