import type { Locale } from '../../i18n.ts'

export type ConvolutionLessonId = 'discrete' | 'probability' | 'signal' | 'image-kernel' | 'polynomial' | 'continuous'

export type ConvolutionLessonCopy = {
  title: string
  what: string
  why: string
  formula: string
  formulaTex: string
  watch: string
}

type LabelMap = Record<string, string>

export type ConvolutionUiCopy = {
  moduleEyebrow: string
  homeSummary: string
  relatedModulesAria: string
  relatedPrefix: string
  controls: string
  seeing: string
  why: string
  formula: string
  values: string
  watch: string
  preset: string
  play: string
  pause: string
  reset: string
  playbackProgress: string
  exportPng: string
  speed: string
  add: string
  yes: string
  no: string
  undefinedValue: string
  noOverlap: string
  operationNote: string
  formulaOperationNote: string
  uploadLocalImage: string
  exportOutputImage: string
  imageProcessingHelp: string
  selectedFunctions: string
  uploadFailed: string
  couldNotReadImage: string
  labels: LabelMap
  canvas: LabelMap
  options: LabelMap
}

export const convolutionLessonCopy: Record<Locale, Record<ConvolutionLessonId, ConvolutionLessonCopy>> = {
  en: {
    discrete: {
      title: 'Discrete Convolution',
      what: 'b is flipped, shifted across a, overlapping values are multiplied, and those products are summed.',
      why: 'This same operation appears in probability, signal filtering, image processing, polynomial multiplication, and Fourier analysis.',
      formula: 'y[k] = sum_i a[i] b[k - i]',
      formulaTex: 'y[k]=\\sum_i a[i]b[k-i]',
      watch: 'If the kernel is symmetric, flipping it does not change it. If it is asymmetric, convolution and correlation differ.',
    },
    probability: {
      title: 'Probability Sum',
      what: 'For a selected sum s, the app finds every pair x + y = s. Each pair contributes P_X(x)P_Y(y), and the output probability is the sum of those contributions.',
      why: 'Adding independent random variables combines their distributions by convolution.',
      formula: 'P(S = s) = sum_x P_X(x) P_Y(s - x)',
      formulaTex: 'P(S=s)=\\sum_x P_X(x)P_Y(s-x)',
      watch: 'The middle sums often have more combinations, which is why two dice are more likely to sum to 7 than to 2 or 12.',
    },
    signal: {
      title: 'Signal Filtering',
      what: 'A kernel is a small group of weights. When it slides to a signal position, some nearby points count more and some count less; their weighted sum becomes the output there.',
      why: 'Changing the kernel changes the filter: averaging smooths, differences highlight changes, and other kernels can sharpen or detect edges.',
      formula: 'y[k] = sum_i signal[i] kernel[k - i]',
      formulaTex: 'y[k]=\\sum_i x[i]h[k-i]',
      watch: 'Smoothing kernels mix nearby points, so small jitter is reduced; real sharp changes can also be softened. Convolution flips the kernel; correlation does not.',
    },
    'image-kernel': {
      title: 'Image Kernel',
      what: 'The kernel center lines up with a pixel. Each kernel number multiplies the matching neighbor color, and the sum becomes the new color at that output position.',
      why: 'Blur, sharpen, emboss, and edge detection can all be expressed as small convolution kernels.',
      formula: 'out[x,y] = sum_u sum_v image[x-u,y-v] kernel[u,v]',
      formulaTex: '\\text{out}[x,y]=\\sum_u\\sum_v I[x-u,y-v]K[u,v]',
      watch: 'Many image-processing kernels are symmetric, but asymmetric kernels reveal the difference between convolution and correlation.',
    },
    polynomial: {
      title: 'Polynomial Multiplication',
      what: 'Every term in one polynomial multiplies every term in the other. Products with the same final power are collected into the same output coefficient.',
      why: 'Collecting equal powers is the same sum pattern as discrete convolution: c[k] collects every pair i + j = k.',
      formula: 'c[k] = sum_i a[i] b[k - i]',
      formulaTex: 'c[k]=\\sum_i a_i b_{k-i}',
      watch: 'The coefficient of x^k collects all pairs i + j = k. Coefficients use ascending powers.',
    },
    continuous: {
      title: 'Continuous Convolution',
      what: 'Continuous convolution does the same kind of operation as discrete convolution: the discrete version multiplies matching entries and adds them; the continuous version multiplies matching curve values and adds the area.',
      why: 'Continuous convolution replaces a discrete sum with an integral. It appears in probability, signal processing, differential equations, and Fourier analysis.',
      formula: '(f * g)(t) = integral f(tau) g(t - tau) d tau',
      formulaTex: '(f*g)(t)=\\int f(\\tau)g(t-\\tau)\\,d\\tau',
      watch: 'For these nonnegative presets, stronger overlap usually gives a larger output. In general, positive and negative regions can cancel.',
    },
  },
  zh: {
    discrete: {
      title: '离散卷积',
      what: 'b 先翻转，再沿着 a 平移；重叠的值逐项相乘，最后把乘积相加。',
      why: '同一个操作会出现在概率、信号滤波、图像处理、多项式乘法和傅里叶分析里。',
      formula: 'y[k] = sum_i a[i] b[k - i]',
      formulaTex: 'y[k]=\\sum_i a[i]b[k-i]',
      watch: '如果卷积核对称，翻转前后没有区别；如果不对称，卷积和相关会得到不同结果。',
    },
    probability: {
      title: '概率和',
      what: '选中一个和 s 时，系统会找出所有 x + y = s 的组合。每个组合贡献 P_X(x)P_Y(y)，把这些贡献加起来，就是这个和的概率。',
      why: '独立随机变量相加时，它们的分布会通过卷积组合。',
      formula: 'P(S = s) = sum_x P_X(x) P_Y(s - x)',
      formulaTex: 'P(S=s)=\\sum_x P_X(x)P_Y(s-x)',
      watch: '中间的和通常有更多组合，所以两个骰子更容易掷出 7，而不是 2 或 12。',
    },
    signal: {
      title: '信号滤波',
      what: '卷积核是一小组权重。它滑到信号的某个位置时，会看附近几个点：有的点权重大，有的点权重小。把这些加权后的点加起来，就是这个位置的输出。',
      why: '改变卷积核就是在改变滤波器：平均会平滑，差分会突出变化，其它卷积核可以锐化或检测边缘。',
      formula: 'y[k] = sum_i signal[i] kernel[k - i]',
      formulaTex: 'y[k]=\\sum_i x[i]h[k-i]',
      watch: '平滑卷积核会把附近的点混在一起，所以小抖动会变少；但真正尖锐的变化也可能被抹平。卷积会翻转卷积核，相关不会。',
    },
    'image-kernel': {
      title: '图像卷积核',
      what: '卷积核的中心对准一个像素。每个卷积核数字会乘上对应的邻居像素颜色。所有结果加起来后，就变成输出图里这个位置的新颜色。',
      why: '模糊、锐化、浮雕和边缘检测都可以用小卷积核表达。',
      formula: 'out[x,y] = sum_u sum_v image[x-u,y-v] kernel[u,v]',
      formulaTex: '\\text{out}[x,y]=\\sum_u\\sum_v I[x-u,y-v]K[u,v]',
      watch: '许多图像处理卷积核是对称的，但不对称卷积核能显示卷积和相关的区别。',
    },
    polynomial: {
      title: '多项式乘法',
      what: '多项式相乘时，每一项都要和另一边的每一项相乘。次数相加后一样的项，会被收集到同一个输出系数里。',
      why: '多项式乘法里的“同次幂合并”，就是卷积里的“同一个 k 收集所有 i+j=k 的项”。',
      formula: 'c[k] = sum_i a[i] b[k - i]',
      formulaTex: 'c[k]=\\sum_i a_i b_{k-i}',
      watch: 'x^k 的系数会收集所有 i + j = k 的项。这里的系数按升幂排列。',
    },
    continuous: {
      title: '连续卷积',
      what: '连续卷积和离散卷积做的是同一类事：离散版是一格一格相乘再相加，连续版是曲线上每一点相乘，再把面积加起来。',
      why: '连续卷积把离散求和换成连续积分，出现在概率、信号处理、微分方程和傅里叶分析里。',
      formula: '(f * g)(t) = integral f(tau) g(t - tau) d tau',
      formulaTex: '(f*g)(t)=\\int f(\\tau)g(t-\\tau)\\,d\\tau',
      watch: '在这些非负预设里，重叠越强，输出通常越大。一般情况下，正负区域可能互相抵消。',
    },
  },
}

export const convolutionUiCopy: Record<Locale, ConvolutionUiCopy> = {
  en: {
    moduleEyebrow: 'Convolution',
    homeSummary: 'Convolution is a sliding measurement: move one object across another, measure how strongly they overlap at each position, multiply the overlap, and sum it into the output.',
    relatedModulesAria: 'Related modules',
    relatedPrefix: 'Related',
    controls: 'Controls',
    seeing: 'What you are seeing',
    why: 'Why it matters',
    formula: 'Current formula',
    values: 'Current values',
    watch: 'Watch for',
    preset: 'Preset',
    play: 'Play',
    pause: 'Pause',
    reset: 'Reset animation',
    playbackProgress: 'Playback progress',
    exportPng: 'Export PNG',
    speed: 'speed',
    add: 'add',
    yes: 'yes',
    no: 'no',
    undefinedValue: 'undefined',
    noOverlap: 'no overlap',
    operationNote: 'Convolution flips the kernel before sliding. Correlation slides the kernel without flipping. For symmetric kernels, both give the same result.',
    formulaOperationNote: 'This formula follows the current operation. Convolution flips the kernel before sliding; correlation slides it directly. Symmetric kernels can make both results match.',
    uploadLocalImage: 'upload local image',
    exportOutputImage: 'Export output image',
    imageProcessingHelp: 'Click either image to inspect a pixel neighborhood. Image processing stays local in the browser.',
    selectedFunctions: 'selected functions',
    uploadFailed: 'Image upload failed.',
    couldNotReadImage: 'Could not read uploaded image.',
    labels: {
      sequenceA: 'sequence a',
      kernelB: 'kernel b',
      mode: 'mode',
      operation: 'operation',
      shiftOutputIndex: 'shift / output index',
      currentK: 'current k',
      yk: 'y[k]',
      overlapCount: 'overlap count',
      kernelSymmetric: 'kernel symmetric',
      terms: 'terms',
      sumS: 'sum s',
      selectedSum: 'selected sum',
      probabilityAtSum: 'P(X + Y = s)',
      ex: 'E[X]',
      ey: 'E[Y]',
      exPlusY: 'E[X + Y]',
      varXPlusY: 'Var(X + Y)',
      signal: 'signal',
      kernel: 'kernel',
      boundaryMode: 'boundary mode',
      length: 'length',
      gaussianSigma: 'gaussian sigma',
      noiseAmplitude: 'noise amplitude',
      seed: 'seed',
      kernelPosition: 'kernel position',
      currentIndex: 'current index',
      kernelSize: 'kernel size',
      outputValue: 'output value',
      sampleImage: 'sample image',
      uploadImage: 'uploaded image',
      kernelPreset: 'kernel preset',
      gridSize: 'kernel size',
      normalizeKernel: 'normalize kernel',
      preserveAlpha: 'preserve alpha',
      grayscaleBeforeApply: 'grayscale before apply',
      selectedPixel: 'selected pixel',
      kernelSum: 'kernel sum',
      outputRgb: 'output RGB',
      inputImage: 'input image',
      outputImage: 'output image',
      aCoefficients: 'A coefficients',
      bCoefficients: 'B coefficients',
      coefficientK: 'coefficient k',
      degreeOfResult: 'degree of result',
      ascendingPowersHelp: 'Ascending powers: [1, 2, 3] means 1 + 2x + 3x^2.',
      functionF: 'function f',
      functionG: 'function g',
      shiftT: 'shift t',
      integrationSamples: 'integration samples',
      currentT: 'current t',
      convolutionValue: '(f * g)(t)',
      sampleCount: 'sample count',
      fPreset: 'f preset',
      gPreset: 'g preset',
      basicControls: 'Basic',
      advancedControls: 'Advanced',
      currentCalculation: 'current calculation',
      appliedKernelFlipped: 'applied kernel (flipped)',
      appliedKernelDirect: 'applied kernel (direct)',
    },
    canvas: {
      discreteAria: 'Discrete convolution scene showing flip, shift, overlap, multiply, sum, and output bars.',
      probabilityAria: 'Probability sum explorer showing source distributions, pair heatmap, and output distribution.',
      signalAria: 'Signal filtering scene showing original signal, kernel window, products, and filtered output.',
      polynomialAria: 'Polynomial multiplication grid and coefficient convolution output.',
      continuousAria: 'Continuous convolution scene showing f, flipped and shifted g, product area, and output curve.',
      aWithFlippedB: 'a (teal) with flipped b (purple)',
      aWithDirectB: 'a (teal) with b sliding directly (purple)',
      overlapProducts: 'overlap products for full index',
      outputY: 'output y',
      pairsForSum: 'pairs that add to selected sum',
      inputSignal: 'input signal',
      kernelFlipped: 'kernel (flipped for convolution)',
      kernelCorrelation: 'kernel (correlation order)',
      filteredOutput: 'filtered output',
      polynomialGrid: 'multiplication grid: row power + column power = output power',
      productCoefficients: 'product coefficients c',
      continuousF: 'f(tau)',
      continuousShiftedG: 'g(t - tau)',
      continuousProduct: 'product area',
      continuousOutputOffset: '(f * g)(t), shifted up',
    },
    options: {
      convolution: 'convolution',
      correlation: 'correlation',
      full: 'full',
      same: 'same',
      valid: 'valid',
      zero: 'zero',
      clamp: 'clamp',
      wrap: 'wrap',
      impulse: 'impulse',
      'impulse identity': 'impulse identity',
      'box blur': 'box blur',
      'edge detector': 'edge detector',
      'small custom': 'small custom',
      'asymmetric kernel': 'asymmetric kernel',
      'symmetric kernel': 'symmetric kernel',
      'fair d6 + fair d6': 'fair d6 + fair d6',
      'biased coin + biased coin': 'biased coin + biased coin',
      'd4 + d8': 'd4 + d8',
      'custom small distribution': 'custom small distribution',
      'repeated dice sum': 'repeated dice sum',
      'binomial coin flips': 'binomial coin flips',
      'The middle sums have the most pairs.': 'The middle sums have the most pairs.',
      'Each sum collects the matching coin outcomes.': 'Each sum collects the matching coin outcomes.',
      'Different supports produce a trapezoid-like sum distribution.': 'Different supports produce a trapezoid-like sum distribution.',
      'Repeated values act like larger probability mass.': 'Repeated values act like larger probability mass.',
      'Repeated convolution builds a bell-shaped dice total.': 'Repeated convolution builds a bell-shaped dice total.',
      'Many independent 0/1 coin flips concentrate near the center.': 'Many independent 0/1 coin flips concentrate near the center.',
      step: 'step',
      sine: 'sine',
      'mixed sine': 'mixed sine',
      'noisy sine': 'noisy sine',
      'random spikes': 'random spikes',
      identity: 'identity',
      'moving average 3': 'moving average 3',
      'moving average 5': 'moving average 5',
      gaussian: 'gaussian',
      difference: 'difference',
      'edge detect': 'edge detect',
      'sharpen-like 1D': 'sharpen-like 1D',
      gradient: 'gradient',
      checkerboard: 'checkerboard',
      'simple face-like pattern': 'simple face-like pattern',
      noise: 'noise',
      'edge shapes': 'edge shapes',
      'uploaded image': 'uploaded image',
      'gaussian blur': 'gaussian blur',
      sharpen: 'sharpen',
      emboss: 'emboss',
      'sobel x': 'sobel x',
      'sobel y': 'sobel y',
      '(1 + x)(1 + x)': '(1 + x)(1 + x)',
      '(1 + x)^2': '(1 + x)^2',
      '(1 + x)^3 step': '(1 + x)^3 step',
      'asymmetric polynomials': 'asymmetric polynomials',
      'negative coefficients': 'negative coefficients',
      'zero coefficients': 'zero coefficients',
      rectangle: 'rectangle',
      triangle: 'triangle',
      'exponential decay': 'exponential decay',
      'two bumps': 'two bumps',
    },
  },
  zh: {
    moduleEyebrow: '卷积',
    homeSummary: '卷积是一种“滑动测量”：把一个对象滑过另一个对象，每个位置都看它们重叠得多强。重叠部分相乘再加起来，就得到这个位置的输出。',
    relatedModulesAria: '相关模块',
    relatedPrefix: '相关',
    controls: '控制',
    seeing: '你正在看到什么',
    why: '为什么重要',
    formula: '当前公式',
    values: '当前数值',
    watch: '注意观察',
    preset: '预设',
    play: '播放',
    pause: '暂停',
    reset: '重置动画',
    playbackProgress: '播放进度',
    exportPng: '导出 PNG',
    speed: '速度',
    add: '添加',
    yes: '是',
    no: '否',
    undefinedValue: '未定义',
    noOverlap: '没有重叠',
    operationNote: '卷积会先翻转卷积核再滑动；相关不会翻转，直接滑动。对称卷积核下，两者结果相同。',
    formulaOperationNote: '这个公式会随当前操作变化。卷积会先翻转卷积核再滑动；相关直接滑动。对称卷积核下，两者结果可能相同。',
    uploadLocalImage: '上传本地图片',
    exportOutputImage: '导出输出图像',
    imageProcessingHelp: '点击任一图像可检查像素邻域。图像处理全部在浏览器本地完成。',
    selectedFunctions: '选中的函数',
    uploadFailed: '图片上传失败。',
    couldNotReadImage: '无法读取上传的图片。',
    labels: {
      sequenceA: '序列 a',
      kernelB: '卷积核 b',
      mode: '模式',
      operation: '操作',
      shiftOutputIndex: '平移 / 输出索引',
      currentK: '当前 k',
      yk: 'y[k]',
      overlapCount: '重叠项数',
      kernelSymmetric: '卷积核是否对称',
      terms: '展开项',
      sumS: '和 s',
      selectedSum: '选中的和',
      probabilityAtSum: 'P(X + Y = s)',
      ex: 'E[X]',
      ey: 'E[Y]',
      exPlusY: 'E[X + Y]',
      varXPlusY: 'Var(X + Y)',
      signal: '信号',
      kernel: '卷积核',
      boundaryMode: '边界模式',
      length: '长度',
      gaussianSigma: '高斯 sigma',
      noiseAmplitude: '噪声幅度',
      seed: '随机种子',
      kernelPosition: '卷积核位置',
      currentIndex: '当前索引',
      kernelSize: '卷积核大小',
      outputValue: '输出值',
      sampleImage: '示例图像',
      uploadImage: '已上传图像',
      kernelPreset: '卷积核预设',
      gridSize: '卷积核大小',
      normalizeKernel: '归一化卷积核',
      preserveAlpha: '保留 alpha',
      grayscaleBeforeApply: '先转灰度',
      selectedPixel: '选中像素',
      kernelSum: '卷积核总和',
      outputRgb: '输出 RGB',
      inputImage: '输入图像',
      outputImage: '输出图像',
      aCoefficients: 'A 系数',
      bCoefficients: 'B 系数',
      coefficientK: '系数 k',
      degreeOfResult: '结果次数',
      ascendingPowersHelp: '升幂排列：[1, 2, 3] 表示 1 + 2x + 3x^2。',
      functionF: '函数 f',
      functionG: '函数 g',
      shiftT: '平移 t',
      integrationSamples: '积分采样数',
      currentT: '当前 t',
      convolutionValue: '(f * g)(t)',
      sampleCount: '采样数',
      fPreset: 'f 预设',
      gPreset: 'g 预设',
      basicControls: '基础',
      advancedControls: '高级',
      currentCalculation: '当前计算',
      appliedKernelFlipped: '实际使用的卷积核（已翻转）',
      appliedKernelDirect: '实际使用的卷积核（直接滑动）',
    },
    canvas: {
      discreteAria: '离散卷积场景，显示翻转、平移、重叠、相乘、求和以及输出柱。',
      probabilityAria: '概率和场景，显示源分布、组合热力图和输出分布。',
      signalAria: '信号滤波场景，显示原始信号、卷积核窗口、乘积和滤波输出。',
      polynomialAria: '多项式乘法网格和系数卷积输出。',
      continuousAria: '连续卷积场景，显示 f、翻转并平移的 g、乘积面积和输出曲线。',
      aWithFlippedB: 'a（青色）与翻转后的 b（紫色）',
      aWithDirectB: 'a（青色）与直接滑动的 b（紫色）',
      overlapProducts: '完整索引的重叠乘积',
      outputY: '输出 y',
      pairsForSum: '加起来等于选中和的组合',
      inputSignal: '输入信号',
      kernelFlipped: '卷积核（卷积时翻转）',
      kernelCorrelation: '卷积核（相关顺序）',
      filteredOutput: '滤波输出',
      polynomialGrid: '乘法网格：行次数 + 列次数 = 输出次数',
      productCoefficients: '乘积系数 c',
      continuousF: 'f(τ)',
      continuousShiftedG: 'g(t−τ)',
      continuousProduct: '乘积面积',
      continuousOutputOffset: '(f * g)(t)，上移显示',
    },
    options: {
      convolution: '卷积',
      correlation: '相关',
      full: 'full',
      same: 'same',
      valid: 'valid',
      zero: '补零',
      clamp: '钳制',
      wrap: '环绕',
      impulse: '冲激',
      'impulse identity': '冲激恒等',
      'box blur': '盒式平滑',
      'edge detector': '边缘检测',
      'small custom': '小型自定义',
      'asymmetric kernel': '非对称卷积核',
      'symmetric kernel': '对称卷积核',
      'fair d6 + fair d6': '公平 d6 + 公平 d6',
      'biased coin + biased coin': '偏置硬币 + 偏置硬币',
      'd4 + d8': 'd4 + d8',
      'custom small distribution': '小型自定义分布',
      'repeated dice sum': '重复骰子求和',
      'binomial coin flips': '二项分布硬币',
      'The middle sums have the most pairs.': '中间的和有最多组合。',
      'Each sum collects the matching coin outcomes.': '每个和都会收集匹配的硬币结果。',
      'Different supports produce a trapezoid-like sum distribution.': '不同支撑会产生近似梯形的和分布。',
      'Repeated values act like larger probability mass.': '重复值相当于更大的概率质量。',
      'Repeated convolution builds a bell-shaped dice total.': '重复卷积会形成钟形的骰子总和分布。',
      'Many independent 0/1 coin flips concentrate near the center.': '许多独立 0/1 硬币会集中在中间。',
      step: '阶跃',
      sine: '正弦',
      'mixed sine': '混合正弦',
      'noisy sine': '含噪正弦',
      'random spikes': '随机尖峰',
      identity: '恒等',
      'moving average 3': '移动平均 3',
      'moving average 5': '移动平均 5',
      gaussian: '高斯',
      difference: '差分',
      'edge detect': '边缘检测',
      'sharpen-like 1D': '一维锐化',
      gradient: '渐变',
      checkerboard: '棋盘格',
      'simple face-like pattern': '简易人脸图案',
      noise: '噪声',
      'edge shapes': '边缘形状',
      'uploaded image': '已上传图像',
      'gaussian blur': '高斯模糊',
      sharpen: '锐化',
      emboss: '浮雕',
      'sobel x': 'Sobel X',
      'sobel y': 'Sobel Y',
      '(1 + x)(1 + x)': '(1 + x)(1 + x)',
      '(1 + x)^2': '(1 + x)^2',
      '(1 + x)^3 step': '(1 + x)^3 分步',
      'asymmetric polynomials': '非对称多项式',
      'negative coefficients': '负系数',
      'zero coefficients': '含零系数',
      rectangle: '矩形',
      triangle: '三角形',
      'exponential decay': '指数衰减',
      'two bumps': '两个凸起',
    },
  },
}
